### ISSUE TITLE
How to use this library for react native

### ISSUE THREAD

**Issue by hungdev** [mattiasw/ExifReader#173] opened 2022-01-17 03:51 UTC
Thank you for your library. 
I hope this library support react native.
![image](https://user-images.githubusercontent.com/12009276/149705394-2d9dd36a-70f0-4179-9166-5d16132a43bc.png)

**Comment by mattiasw** [comment] 2022-01-17 07:59
Hi! I think I know what the problem is. I will try to look at it later today or tomorrow.

**Comment by mattiasw** [comment] 2022-01-17 20:03
So, it wasn't exactly the issue I thought and I'm not used to React Native so I can't easily test this, but I have put up a branch. Could you try it? If you want to do it through `package.json` you should be able to use this string: `github:mattiasw/ExifReader#173-react-native`

**Comment by mattiasw** [comment] 2022-01-20 20:45
Just to rule that out, does the image work here? https://mattiasw.github.io/ExifReader/esm/
But now that I see it's a local file that is being used with the path starting with `file://` I'm a bit skeptical that it will work automatically. Setting up React Native and get into that enough to being able to work this out is a bit big of a task for me, at least right now. There is another route though and that would be for you to load the file yourself into an ArrayBuffer and then pass that into ExifReader. I assume this is possible with React Native and probably not that much code either because it's not that tricky in the browser or in Node. And I know others have been using ExifReader with React Native before.

**Comment by hungdev** [comment] 2022-01-21 08:17
@mattiasw I love you so much <3
It worked for me. I hope you merge it to master and update readme for react native usage.
For those who come later:
```
import RNFS from 'react-native-fs';
import { decode } from 'base64-arraybuffer';
import ExifReader from 'exifreader';

const b64 = await RNFS.readFile('YOUR IMAGE URI', 'base64') // for example ios uri: "file:///Users/cee/Library/Developer/CoreSimulator/Devices/023F37A5-5403-429C-85C0-48E2F15B62BB/data/Containers/Data/Application/94A7EA17-518B-4608-8652-EA527FD5D8A0/tmp/IMG_4194.HEIC"
const arrbf = decode(b64)
const tags = await ExifReader.load(arrbf, { expanded: true });
console.log('tags', tags)
```

**Comment by mattiasw** [comment] 2022-01-23 16:02
🤗 I've merged and released it as version 4.2.0. Also added your example code to the README. Thanks for helping to make this library better!

**Closed by mattiasw** 2022-01-23 16:02 UTC

**Comment by tomgreco** [comment] 2022-02-25 21:06
@mattiasw I have version 4.2 and I'm getting the exact same error message in the original post about missing https package.
Any idea how to resolve this issue? I'm on latest react-native version.

**Comment by hungdev** [comment] 2022-02-26 06:55
@mattiasw last time i built source from your react native branch and i edited main path from `dist` to `src`. And i didnt install your lib from npm.
<img width="750" alt="image" src="https://user-images.githubusercontent.com/12009276/155833245-75af81d3-d0f3-4b36-816a-81aa48ddac31.png">
Can you check it again?

**Comment by mattiasw** [comment] 2022-02-26 11:55
@tomgreco What do you pass in to ExifReader? Do you follow these instructions for React Native: https://github.com/mattiasw/ExifReader#using-react-native

@hungdev When the branch was merged and the new version published to npm, that branch was deleted. You should not have to edit the `package.json` file if you install from npm.

**Comment by mattiasw** [comment] 2022-02-26 13:30
Very weird. It can only reach that part of the code if a string is passed in and the string starts with `http` so I'm not sure what is going on here. I'm guessing the compilation step of React Native tries to do something I'm not aware of. If I ever get to setting up React Native I will have a look but that is not planned right now.

**Comment by tomgreco** [comment] 2022-02-26 14:11
The error is occurring during compile time not run time. If that helps shed light on what is happening.

**Comment by hungdev** [comment] 2022-02-26 15:15
> @tomgreco What do you pass in to ExifReader? Do you follow these instructions for React Native? https://github.com/mattiasw/ExifReader#using-react-native
> 
> @hungdev When the branch was merged and the new version published to npm, that branch was deleted. You should not have to edit the `package.json` file if you install from npm.

Since you told me to pull from the react native branch, I have never npm i or pulled again.

**Comment by mattiasw** [comment] 2022-02-26 19:53
@tomgreco Yes, that is helpful, thanks. I have a theory on why it happens but I'm not sure how to fix it. Maybe it would work if one would import the library by using the full path to the main source file instead of the transpiled version: `node_modules/exifreader/src/exif-reader.js`. But I'm not sure.

@hungdev It was meant as a temporary test, just to see if it helped in any way. :-)

**Comment by mattiasw** [comment] 2022-03-03 19:42
I will have a proper look at this myself in #182.

**Comment by a-vikor** [comment] 2023-05-24 14:45
To work remote images in a TS React Native project, read this: https://github.com/mattiasw/ExifReader/issues/182#issuecomment-1561295101.
