### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by krmax44** [mattiasw/ExifReader#239] opened 2023-06-19 10:51 UTC
### Description

When installing with Yarn, I get the following error:

```
Command: node bin/build.js --only-with-config
Arguments:
Directory: node_modules/exifreader
Output:
/bin/sh: webpack: command not found
node:child_process:960
    throw err;
    ^

Error: Command failed: webpack
```

I believe it's because of these lines:

https://github.com/mattiasw/ExifReader/blob/fe4bc827d6559158e90acada65400854e32de7e5/bin/build.js#L38-L45

In my testing, this function always returns `true`, since `npm ls webpack` exits with `0` even when webpack is not installed.

Therefore, the script won't install webpack as it assumes it's already there, which results in an error when it tries to execute webpack.

**Additional details**

- ExifReader version: 4.12.1
- Web browser and version: - 
- Node version: v20.1.0
- Can you reproduce the bug on the examples site? If so, using which implementation (global object, AMD, and/or ES module)? https://mattiasw.github.io/ExifReader/

**How to reproduce**

`yarn install exifreader`

**Comment by mattiasw** [comment] 2023-06-23 17:21
Hi! `yarn install exifreader` works fine for me (except it complained that `install` has been replaced with `add`). Are you using the custom build settings in your `package.json`? I'm wondering because it shouldn't run the webpack code at all for non-custom builds. Could you maybe create a minimal reproducible example that I can try out?

**Comment by krmax44** [comment] 2023-07-07 10:13
It's difficult for me to reproduce reliably. [Happened in our CI yesterday again](https://github.com/okfde/froide/actions/runs/5475072672/jobs/9970668892#step:6:548), but disappeared by itself.

**Comment by mattiasw** [comment] 2023-07-07 19:37
That looks like another error than in the first comment. And I had the exact same one around the same time yesterday (`Cannot read properties of undefined (reading 'addHelper')`). I have never seen the error before and it started working a couple of hours later so my guess is there was something strange going on with npm and/or one of the babel packages.

**Comment by mattiasw** [comment] 2023-10-27 10:07
Closing this since it looks to have been a temporary error.

**Closed by mattiasw** 2023-10-27 10:07 UTC
